aws_access_key = "AQIA40QKF3URNPHMYR04"
aws_secret_key = "oNOERet2zumJ9mrqf/dApzXQEUBaUDvm7lPqfscE"
rds_instance_identifier = "terraform-mysql"
database_name = "terraform_test_db"
database_user = "terraform"
